{% set name = "am3" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.desy.de/am3/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 92afb78f9c9aeeadfa373ce9f507e3a16939d3c70fa38ddcd901467df589cbe5

build:
  skip: true  # [win]
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build: # here go the tools needed to compile the code
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host: # here go the dependencies needed for includes etc
    - python
    - pip
    - pybind11
    - eigen
    - gsl
    - libopenblas   # [linux]
    - libgomp       # [linux]
    - llvm-openmp   # [osx]
    - numpy
    - scikit-build-core
  run: # here goes what the user needs to run it
    - python

test:
  imports:
    - am3
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.desy.de/am3/am3
  summary: 'Astrophysical Multi-Messenger Modeling (AM³) Software'
  description: |
    AM³ is a software package for simulating lepto-hadronic interactions in astrophysical environments. 
    It solves the time-dependent partial differential equations for the energy spectra of electrons, 
    positrons, protons, neutrons, photons, neutrinos as well as charged secondaries (pions and muons), 
    immersed in an isotropic magnetic field. Crucially, it accounts for the fact that photons and 
    charged secondaries emitted in electromagnetic and hadronic interactions feed back into the 
    interaction rates in a time-dependent manner, therefore grasping non-linear effects including 
    electromagnetic cascades.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://am3.readthedocs.io/en/latest/
  dev_url: https://gitlab.desy.de/am3/am3

extra:
  recipe-maintainers:
    - maklinger
    - xrod
